name: Handle Issue Form

on: 
  issues:
    types:
      - labeled

permissions:
  contents: read
  actions: write
  issues: write

env:
  USER: ${{ github.event.issue.user.login }}

jobs:
  handle-issue-request:
    name: Handle issue request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.OCTODESK_APP_ID }}
          private-key: ${{ secrets.OCTODESK_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Add In Progress Comment To Issue
        shell: bash
        run: |
          gh issue comment ${{ github.event.issue.id }} -b "@${USER} a [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) was started to handle your request"
      - name: Parse Issue Form into JSON
        id: parse
        uses: zentered/issue-forms-body-parser@v2.2.0
      - name: Repository Request
        if: github.event.label.name == 'repo-request'
        uses: ./github/actions/repository-requst/
        with:
          issue-json: ${{ steps.parse.outputs.data }}
      - name: Team Membership Requst
        uses: ./.github/actions/team-membership-request/
        with:
          issue-json: ${{ steps.parse.outputs.data }}
      - name: Add Failure Comment To Issue
        if: failure()
        shell: bash
        run: |
          gh issue comment ${{ github.event.issue.id }} -b message: "@${USER} the workflow failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details."
      - name: Close Issue With Success Comment
        if: success()
        shell: bash
        run: |
          gh issue close ${{ github.event.issue.id }} \
            -r completed \
            -c "@${USER} your request was handled successfully."